// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Darkwater Egg
 * {1}
 * Artifact
 * {2}, {T}, Sacrifice this artifact: Add {U}{B}. Draw a card.
 */
val DarkwaterEgg = card("Darkwater Egg") {
    manaCost = "{1}"
    colorIdentity = "UB"
    typeLine = "Artifact"
    oracleText = "{2}, {T}, Sacrifice this artifact: Add {U}{B}. Draw a card."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}"), Costs.Tap, Costs.SacrificeSelf)
        effect = Effects.Composite(
            Effects.Composite(Effects.AddMana(Color.BLUE, 1), Effects.AddMana(Color.BLACK, 1)),
            DrawCardsEffect(1)
        )
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "299"
        artist = "David Martin"
        flavorText = "\"Do you thirst for knowledge no matter the cost?\"\n—Watnik, master glassblower"
        imageUri = "https://cards.scryfall.io/normal/front/f/b/fb988572-1e1d-4b1d-8dc7-78bda966554e.jpg"
    }
}
