// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ody.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.DrawCardsEffect


/**
 * Mossfire Egg
 * {1}
 * Artifact
 * {2}, {T}, Sacrifice this artifact: Add {R}{G}. Draw a card.
 */
val MossfireEgg = card("Mossfire Egg") {
    manaCost = "{1}"
    colorIdentity = "RG"
    typeLine = "Artifact"
    oracleText = "{2}, {T}, Sacrifice this artifact: Add {R}{G}. Draw a card."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}"), Costs.Tap, Costs.SacrificeSelf)
        effect = Effects.Composite(
            Effects.Composite(Effects.AddMana(Color.RED, 1), Effects.AddMana(Color.GREEN, 1)),
            DrawCardsEffect(1)
        )
        manaAbility = true
        timing = TimingRule.ManaAbility
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "304"
        artist = "David Martin"
        flavorText = "\"Can you feel your instincts overwhelm your reason?\"\n—Watnik, master glassblower"
        imageUri = "https://cards.scryfall.io/normal/front/1/f/1fd66433-b0e9-453d-9a27-ea0efb158dac.jpg"
    }
}
