// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.hob.cards

import com.wingedsheep.sdk.core.Counters
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.CantBeBlockedBy
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.AddCountersEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Duskwatch Hunter
 * {2}{B/G}
 * Creature — Wolf
 * 3/1
 * This creature can't be blocked by tokens.
 * When this creature enters, put a +1/+1 counter on target creature.
 */
val DuskwatchHunter = card("Duskwatch Hunter") {
    manaCost = "{2}{B/G}"
    colorIdentity = "BG"
    typeLine = "Creature — Wolf"
    oracleText = "This creature can't be blocked by tokens.\nWhen this creature enters, put a +1/+1 counter on target creature."
    power = 3
    toughness = 1
    staticAbility {
        ability = CantBeBlockedBy(blockerFilter = GameObjectFilter.Permanent)
    }
    triggeredAbility {
        trigger = Triggers.EntersBattlefield
        val t = target("target", TargetCreature(filter = TargetFilter.Creature))
        effect = AddCountersEffect(counterType = Counters.PLUS_ONE_PLUS_ONE, count = 1, target = t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "153"
        artist = "Samuele Bandini"
        flavorText = "Packs of evil wolves lived under the shadow of the Goblin-infested mountains, over the Edge of the Wild on the borders of the unknown."
        imageUri = "https://cards.scryfall.io/normal/front/3/6/3685c783-d837-4466-a960-ab3098db64c3.jpg"
    }
}
