// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.hob.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Targets
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GrantKeyword
import com.wingedsheep.sdk.scripting.ModifyStats
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Eagle's Rescue
 * {2}{W/U}{W/U}
 * Enchantment — Aura
 * Enchant creature
 * Enchanted creature gets +2/+2 and has flying.
 * {2}{W/U}{W/U}: Return this card from your graveyard to the battlefield attached to target creature you control with power 1 or less. Activate only as a sorcery.
 */
val EaglesRescue = card("Eagle's Rescue") {
    manaCost = "{2}{W/U}{W/U}"
    colorIdentity = "WU"
    typeLine = "Enchantment — Aura"
    oracleText = "Enchant creature\nEnchanted creature gets +2/+2 and has flying.\n{2}{W/U}{W/U}: Return this card from your graveyard to the battlefield attached to target creature you control with power 1 or less. Activate only as a sorcery."
    auraTarget = Targets.Creature
    staticAbility {
        ability = ModifyStats(2, 2)
    }
    staticAbility {
        ability = GrantKeyword(Keyword.FLYING)
    }
    activatedAbility {
        cost = Costs.Mana("{2}{W/U}{W/U}")
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.powerAtMost(1).youControl()))
        effect = Effects.Move(EffectTarget.Self, Zone.BATTLEFIELD, fromZone = Zone.GRAVEYARD)
        timing = TimingRule.SorcerySpeed
        activateFromZone = Zone.GRAVEYARD
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "155"
        artist = "Ramza Psyru"
        flavorText = "\"Don't pinch! You need not be frightened like a rabbit. What is finer than flying?\""
        imageUri = "https://cards.scryfall.io/normal/front/1/2/12c8f2cc-ac9d-4cf6-9025-efe366b4e07f.jpg"
    }
}
