// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.hob.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.SearchDestination


/**
 * Troop of Ponies
 * {2}
 * Creature — Horse
 * 2/1
 * {2}, {T}, Sacrifice this creature: Search your library for up to two basic land cards, reveal them, put one onto the battlefield tapped and the other into your hand, then shuffle.
 */
val TroopOfPonies = card("Troop of Ponies") {
    manaCost = "{2}"
    colorIdentity = ""
    typeLine = "Creature — Horse"
    oracleText = "{2}, {T}, Sacrifice this creature: Search your library for up to two basic land cards, reveal them, put one onto the battlefield tapped and the other into your hand, then shuffle."
    power = 2
    toughness = 1
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}"), Costs.Tap, Costs.SacrificeSelf)
        effect = Patterns.Library.searchLibrary(
            filter = GameObjectFilter.BasicLand,
            count = 2,
            destination = SearchDestination.HAND,
            entersTapped = true,
            reveal = true
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "3"
        artist = "Christina Kraus"
        flavorText = "The sun had only just turned west when they started on the path to Mirkwood, and till evening it lay golden on the land about them."
        imageUri = "https://cards.scryfall.io/normal/front/0/b/0b4b1c59-bcec-4779-9e27-0e6f9feb4e11.jpg"
    }
}
